# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [2]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [3]:
A = np.arange(1, 16).reshape(3,5)

In [4]:
print(A.ndim)
print(A.shape)
print(A.size)
print(A.dtype)

2
(3, 5)
15
int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [5]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [6]:
print(B-C)
print()
print(B*C)
print()
print(B @ C)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [7]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
print(np.exp(B))
print(np.min(B))
print(B.min(axis=1))
print(B.min(axis=0))
print(np.argmin(B))
print(np.argmin(B, axis=1))
print(np.sum(B))
print(np.mean(B, axis=0))
print(np.median(B, axis=0))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
1
[1 4 7]
[1 2 3]
0
[0 0 0]
45
[4. 5. 6.]
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [9]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [10]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

it shows you the array at position 1

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [11]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [12]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [13]:

for j in np.nditer(A):
    print(j, end=' ')

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 

### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [14]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


it reshapes the array to an array of two arrays each containing three arrays

# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [15]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [16]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [17]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [18]:
def add_mult_matrices(ndarray_1, ndarray_2, operator):
    if isinstance(ndarray_1,np.ndarray) and isinstance(ndarray_2,np.ndarray):
        if operator == "add":
            sum = np.add(ndarray_1,ndarray_2)
            return sum
        elif operator == "multiply":
            sum = np.matmul(ndarray_1,ndarray_2)
            return sum
        else:
            raise Exception('operator must either be "add" or "multiply"')
    else:
        raise ValueError('both arrays must be numpy.ndarray')

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. 

In [19]:
x = np.array([4,3])
print(x)
print(' ')
#a 2
print('10.1.1')
print(' ')
print('b')
print (5*x)

print(' ')
print('c')
print (3*x)

print(' ')
print('d')
print(5*x + 3*x)

print(' ')
print('e')
print(8*x)

print(' ')
print('f')
print(4*x-x)

print(' ')
print('g')
print(x.transpose())

print (' ')
print('h')
print('nej')

print (' ')
print('i')
print(np.average(x))

[4 3]
 
10.1.1
 
b
[20 15]
 
c
[12  9]
 
d
[32 24]
 
e
[32 24]
 
f
[12  9]
 
g
[4 3]
 
h
nej
 
i
3.5


In [20]:
print('10.1.2')
v = np.array([[3],[7],[0],[11]])
print(v)

print(' ')
print('a')
print(v.shape)

print(' ')
print('b')
print(v*2)

print(' ')
print('c')
print(v*5 + v*2)

print(' ')
print('d')
print(v*4 - v*2)

print(' ')
print('e')
vt = np.transpose(v)
print(vt.shape)

print(' ')
print('f')
print(np.average(v))

10.1.2
[[ 3]
 [ 7]
 [ 0]
 [11]]
 
a
(4, 1)
 
b
[[ 6]
 [14]
 [ 0]
 [22]]
 
c
[[21]
 [49]
 [ 0]
 [77]]
 
d
[[ 6]
 [14]
 [ 0]
 [22]]
 
e
(1, 4)
 
f
5.25


In [21]:
print('10.1.2')
v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])
print(v1)
print(v2)

print(' ')
print('a')
print(np.average(v1))

print(' ')
print('b')
print(np.average(v1-v2))

10.1.2
[4 3 1 5]
[2 3 1 1]
 
a
3.25
 
b
1.5


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

In [22]:
A = np.matrix('2 1 -1; 1 -1 1')
B = np.matrix('4 -2 1; 2 -4 -2')
C = np.matrix('1 2; 2 1')
D = np.matrix('3 4; 4 3')
E = np.matrix('1; 2')
I = np.matrix('1 0; 0 1')

print(' ')
print('A')
print(2*A)

print(' ')
print('B')
print(B-2*A)

print(' ')
print('C')
print('3C-2E: Not defined')

print(' ')
print('D')
print(2*D-3*C)

print(' ')
print('E')
print(np.transpose(D)+ 2*D)

print(' ')
print('F')
print(np.transpose(2*C)-np.transpose(2*D))

print(' ')
print('G')
print('np.transpose(A)-B not defined')

print(' ')
print('H')
print('A*C not defined')

print(' ')
print('I')
print(C*D)

print(' ')
print('J')
print('B*C not defined')

print(' ')
print('I')
print(C*I)

print(' ')
print('L')
print(A*np.transpose(B))

 
A
[[ 4  2 -2]
 [ 2 -2  2]]
 
B
[[ 0 -4  3]
 [ 0 -2 -4]]
 
C
3C-2E: Not defined
 
D
[[3 2]
 [2 3]]
 
E
[[ 9 12]
 [12  9]]
 
F
[[-4 -4]
 [-4 -4]]
 
G
np.transpose(A)-B not defined
 
H
A*C not defined
 
I
[[11 10]
 [10 11]]
 
J
B*C not defined
 
I
[[1 2]
 [2 1]]
 
L
[[5 2]
 [7 4]]


In [23]:
A = np.matrix('2 3 4; 5 4 1')

print('10.2.2')
print(' ')
print(A*np.transpose(A))

10.2.2
 
[[29 26]
 [26 42]]


In [24]:
A = np.matrix('1 2; 2 4')
B = np.matrix('2 1; 1 3')
C = np.matrix('4 3; 0 2')

print('10.2.3')
print('A*B = A*C:', (A*B == A*C).all())
print('B = C:', (B == C).all()) 

10.2.3
A*B = A*C: True
B = C: False


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [25]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [26]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [27]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


because v2 isn't a seperate array from v1 but instead simply refers to v1 any changes made to v2 will change v1